VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "clsBloqueHE"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Explicit

'=========================================
' BLOQUE DE HORAS EXTRA
'=========================================
Public Inicio As Date
Public Fin As Date
Public Duracion As Double
