[theme]
base = "dark"
primaryColor = "#F58220"
backgroundColor = "#121418"
secondaryBackgroundColor = "#1A1D24"
textColor = "#FFFFFF"
font = "sans serif"

[server]
headless = true
enableStaticServing = true

[client]
toolbarMode = "minimal"
showErrorDetails = false


